name: ${project.name}
main: wtf.choco.alchema.Alchema
version: ${project.version}
description: ${project.description}
author: Choco
website: https://choco.wtf
api-version: 1.16

commands:
  alchema:
    description: The main command for Alchema
    usage: /<command> <version|reload>
  givevialofessence:
    description: Give a vial of essence to a player
    usage: /<command> [player] [amount] [entity] [amount of essence]
    aliases: [ givevialsofessence, giveessence, givevials, givevial ]
    permission: alchema.command.givevialofessence

permissions:
  alchema.command.*:
    description: Grants access to all commands provided by Alchema
    default: op
    children:
      alchema.command.reload: true
      alchema.command.integrations: false
      alchema.command.givevialofessence: true

  alchema.command.reload:
    description: Grants access to the /alchema reload subcommand
    default: op
  alchema.command.integrations:
    description: Grants access to the /alchema integrations subcommand
    default: true
  alchema.command.givevialofessence:
    description: Grants access to the /givevialofessence command
    default: op

  alchema.updatenotify:
    description: Grants the ability to see update notifications on join
    default: op
