name: ${project.name}
main: wtf.choco.alchema.Alchema
version: ${project.version}
description: ${project.description}
author: Choco
website: https://choco.wtf
api-version: 1.16

commands:
  alchema:
    description: The main command for Alchema
    usage: /<command> <version|reload>
  givevialofessence:
    description: Give a vial of essence to a player
    usage: /<command> <entity> [amount of essence] [player] [amount]
    aliases: [ givevialsofessence, giveessence ]
    permission: alchema.command.givevialofessence

permissions:
  alchema.command.reload:
    description: Grants access to the /alchema reload subcommand
    default: op
  alchema.command.integrations:
    description: Grants access to the /alchema integrations subcommand
    default: true
  alchema.command.givevialofessence:
    description: Grants access to the /givevialofessence command
    default: op

