name: ${project.name}
main: wtf.choco.alchema.Alchema
version: ${project.version}
description: ${project.description}
author: Choco
website: https://choco.wtf
api-version: 1.16

commands:
  alchema:
    description: The main command for Alchema
    usage: /<command> <version|reload>

permissions:
  alchema.command.*:
    description: Grants access to all commands provided by Alchema
    default: op
    children:
      alchema.command.reload: true
      alchema.command.integrations: false

  alchema.command.reload:
    description: Grants access to the /alchema reload subcommand
    default: op
  alchema.command.integrations:
    description: Grants access to the /alchema integrations subcommand
    default: true

  alchema.updatenotify:
    description: Grants the ability to see update notifications on join
    default: op
